// SQL Practice Tracker — seed data.
// Add new questions by appending objects to this array. Saved progress is keyed by `id`,
// so existing notes/status/solutions survive when you add or re-order questions here.
//
//   { id, title, difficulty: "Easy"|"Medium"|"Hard",
//     topic: "Basics"|"Joins"|"Aggregation"|"Subqueries"|"Window"|"String"|"Date"|"Pivot",
//     url, done }   // done:true = already solved (seeds status "Solved")

const QUESTIONS = [
  { id: 175,  title: "Combine Two Tables", difficulty: "Easy",   topic: "Joins",       url: "https://leetcode.com/problems/combine-two-tables/", done: true },
  { id: 176,  title: "Second Highest Salary", difficulty: "Medium", topic: "Subqueries", url: "https://leetcode.com/problems/second-highest-salary/", done: true },
  { id: 177,  title: "Nth Highest Salary", difficulty: "Medium", topic: "Subqueries",  url: "https://leetcode.com/problems/nth-highest-salary/", done: true },
  { id: 178,  title: "Rank Scores", difficulty: "Medium", topic: "Window",             url: "https://leetcode.com/problems/rank-scores/", done: true },
  { id: 180,  title: "Consecutive Numbers", difficulty: "Medium", topic: "Window",     url: "https://leetcode.com/problems/consecutive-numbers/", done: true },
  { id: 181,  title: "Employees Earning More Than Their Managers", difficulty: "Easy", topic: "Joins", url: "https://leetcode.com/problems/employees-earning-more-than-their-managers/", done: true },
  { id: 182,  title: "Duplicate Emails", difficulty: "Easy", topic: "Aggregation",     url: "https://leetcode.com/problems/duplicate-emails/", done: true },
  { id: 183,  title: "Customers Who Never Order", difficulty: "Easy", topic: "Subqueries", url: "https://leetcode.com/problems/customers-who-never-order/", done: true },
  { id: 184,  title: "Department Highest Salary", difficulty: "Medium", topic: "Subqueries", url: "https://leetcode.com/problems/department-highest-salary/", done: true },
  { id: 185,  title: "Department Top Three Salaries", difficulty: "Hard", topic: "Window", url: "https://leetcode.com/problems/department-top-three-salaries/", done: true },
  { id: 196,  title: "Delete Duplicate Emails", difficulty: "Easy", topic: "Joins",    url: "https://leetcode.com/problems/delete-duplicate-emails/", done: true },
  { id: 197,  title: "Rising Temperature", difficulty: "Easy", topic: "Joins",         url: "https://leetcode.com/problems/rising-temperature/", done: true },
  { id: 262,  title: "Trips and Users", difficulty: "Hard", topic: "Aggregation",      url: "https://leetcode.com/problems/trips-and-users/", done: false },
  { id: 511,  title: "Game Play Analysis I", difficulty: "Easy", topic: "Aggregation", url: "https://leetcode.com/problems/game-play-analysis-i/", done: true },
  { id: 550,  title: "Game Play Analysis IV", difficulty: "Medium", topic: "Window",   url: "https://leetcode.com/problems/game-play-analysis-iv/", done: false },
  { id: 570,  title: "Managers with at Least 5 Direct Reports", difficulty: "Medium", topic: "Aggregation", url: "https://leetcode.com/problems/managers-with-at-least-5-direct-reports/", done: true },
  { id: 577,  title: "Employee Bonus", difficulty: "Easy", topic: "Joins",             url: "https://leetcode.com/problems/employee-bonus/", done: true },
  { id: 584,  title: "Find Customer Referee", difficulty: "Easy", topic: "Basics",     url: "https://leetcode.com/problems/find-customer-referee/", done: true },
  { id: 585,  title: "Investments in 2016", difficulty: "Medium", topic: "Aggregation", url: "https://leetcode.com/problems/investments-in-2016/", done: true },
  { id: 586,  title: "Customer Placing the Largest Number of Orders", difficulty: "Easy", topic: "Aggregation", url: "https://leetcode.com/problems/customer-placing-the-largest-number-of-orders/", done: true },
  { id: 595,  title: "Big Countries", difficulty: "Easy", topic: "Basics",             url: "https://leetcode.com/problems/big-countries/", done: true },
  { id: 596,  title: "Classes With at Least 5 Students", difficulty: "Easy", topic: "Aggregation", url: "https://leetcode.com/problems/classes-more-than-5-students/", done: true },
  { id: 601,  title: "Human Traffic of Stadium", difficulty: "Hard", topic: "Window",  url: "https://leetcode.com/problems/human-traffic-of-stadium/", done: true },
  { id: 602,  title: "Friend Requests II: Who Has the Most Friends", difficulty: "Medium", topic: "Aggregation", url: "https://leetcode.com/problems/friend-requests-ii-who-has-the-most-friends/", done: true },
  { id: 607,  title: "Sales Person", difficulty: "Easy", topic: "Subqueries",          url: "https://leetcode.com/problems/sales-person/", done: true },
  { id: 608,  title: "Tree Node", difficulty: "Medium", topic: "Basics",              url: "https://leetcode.com/problems/tree-node/", done: true },
  { id: 610,  title: "Triangle Judgement", difficulty: "Easy", topic: "Basics",        url: "https://leetcode.com/problems/triangle-judgement/", done: true },
  { id: 619,  title: "Biggest Single Number", difficulty: "Easy", topic: "Aggregation", url: "https://leetcode.com/problems/biggest-single-number/", done: true },
  { id: 620,  title: "Not Boring Movies", difficulty: "Easy", topic: "Basics",         url: "https://leetcode.com/problems/not-boring-movies/", done: true },
  { id: 626,  title: "Exchange Seats", difficulty: "Medium", topic: "Window",          url: "https://leetcode.com/problems/exchange-seats/", done: false },
  { id: 627,  title: "Swap Salary", difficulty: "Easy", topic: "String",               url: "https://leetcode.com/problems/swap-salary/", done: false },
  { id: 1045, title: "Customers Who Bought All Products", difficulty: "Medium", topic: "Aggregation", url: "https://leetcode.com/problems/customers-who-bought-all-products/", done: true },
  { id: 1050, title: "Actors and Directors Who Cooperated At Least Three Times", difficulty: "Easy", topic: "Aggregation", url: "https://leetcode.com/problems/actors-and-directors-who-cooperated-at-least-three-times/", done: true },
  { id: 1068, title: "Product Sales Analysis I", difficulty: "Easy", topic: "Joins",   url: "https://leetcode.com/problems/product-sales-analysis-i/", done: true },
  { id: 1070, title: "Product Sales Analysis III", difficulty: "Medium", topic: "Window", url: "https://leetcode.com/problems/product-sales-analysis-iii/", done: false },
  { id: 1075, title: "Project Employees I", difficulty: "Easy", topic: "Aggregation",  url: "https://leetcode.com/problems/project-employees-i/", done: false },
  { id: 1084, title: "Sales Analysis III", difficulty: "Easy", topic: "Aggregation",   url: "https://leetcode.com/problems/sales-analysis-iii/", done: false },
  { id: 1141, title: "User Activity for the Past 30 Days I", difficulty: "Easy", topic: "Aggregation", url: "https://leetcode.com/problems/user-activity-for-the-past-30-days-i/", done: false },
  { id: 1148, title: "Article Views I", difficulty: "Easy", topic: "Basics",           url: "https://leetcode.com/problems/article-views-i/", done: false },
  { id: 1158, title: "Market Analysis I", difficulty: "Medium", topic: "Joins",        url: "https://leetcode.com/problems/market-analysis-i/", done: false },
  { id: 1164, title: "Product Price at a Given Date", difficulty: "Medium", topic: "Subqueries", url: "https://leetcode.com/problems/product-price-at-a-given-date/", done: false },
  { id: 1174, title: "Immediate Food Delivery II", difficulty: "Medium", topic: "Aggregation", url: "https://leetcode.com/problems/immediate-food-delivery-ii/", done: false },
  { id: 1179, title: "Reformat Department Table", difficulty: "Easy", topic: "Pivot",  url: "https://leetcode.com/problems/reformat-department-table/", done: false },
  { id: 1193, title: "Monthly Transactions I", difficulty: "Medium", topic: "Aggregation", url: "https://leetcode.com/problems/monthly-transactions-i/", done: false },
  { id: 1204, title: "Last Person to Fit in the Bus", difficulty: "Medium", topic: "Window", url: "https://leetcode.com/problems/last-person-to-fit-in-the-bus/", done: false },
  { id: 1211, title: "Queries Quality and Percentage", difficulty: "Easy", topic: "Aggregation", url: "https://leetcode.com/problems/queries-quality-and-percentage/", done: false },
  { id: 1251, title: "Average Selling Price", difficulty: "Easy", topic: "Joins",      url: "https://leetcode.com/problems/average-selling-price/", done: false },
  { id: 1280, title: "Students and Examinations", difficulty: "Easy", topic: "Joins",  url: "https://leetcode.com/problems/students-and-examinations/", done: false },
  { id: 1321, title: "Restaurant Growth", difficulty: "Medium", topic: "Window",       url: "https://leetcode.com/problems/restaurant-growth/", done: false },
  { id: 1327, title: "List the Products Ordered in a Period", difficulty: "Easy", topic: "Joins", url: "https://leetcode.com/problems/list-the-products-ordered-in-a-period/", done: false },
  { id: 1341, title: "Movie Rating", difficulty: "Medium", topic: "Aggregation",       url: "https://leetcode.com/problems/movie-rating/", done: false },
  { id: 1378, title: "Replace Employee ID With The Unique Identifier", difficulty: "Easy", topic: "Joins", url: "https://leetcode.com/problems/replace-employee-id-with-the-unique-identifier/", done: false },
  { id: 1393, title: "Capital Gain/Loss", difficulty: "Medium", topic: "Aggregation",  url: "https://leetcode.com/problems/capital-gainloss/", done: false },
  { id: 1407, title: "Top Travellers", difficulty: "Easy", topic: "Joins",             url: "https://leetcode.com/problems/top-travellers/", done: false },
  { id: 1484, title: "Group Sold Products By The Date", difficulty: "Easy", topic: "Aggregation", url: "https://leetcode.com/problems/group-sold-products-by-the-date/", done: false },
  { id: 1517, title: "Find Users With Valid E-Mails", difficulty: "Easy", topic: "String", url: "https://leetcode.com/problems/find-users-with-valid-e-mails/", done: false },
  { id: 1527, title: "Patients With a Condition", difficulty: "Easy", topic: "String", url: "https://leetcode.com/problems/patients-with-a-condition/", done: false },
  { id: 1581, title: "Customer Who Visited but Did Not Make Any Transactions", difficulty: "Easy", topic: "Joins", url: "https://leetcode.com/problems/customer-who-visited-but-did-not-make-any-transactions/", done: false },
  { id: 1587, title: "Bank Account Summary II", difficulty: "Easy", topic: "Aggregation", url: "https://leetcode.com/problems/bank-account-summary-ii/", done: false },
  { id: 1633, title: "Percentage of Users Attended a Contest", difficulty: "Easy", topic: "Aggregation", url: "https://leetcode.com/problems/percentage-of-users-attended-a-contest/", done: false },
  { id: 1661, title: "Average Time of Process per Machine", difficulty: "Easy", topic: "Aggregation", url: "https://leetcode.com/problems/average-time-of-process-per-machine/", done: false },
  { id: 1667, title: "Fix Names in a Table", difficulty: "Easy", topic: "String",      url: "https://leetcode.com/problems/fix-names-in-a-table/", done: false },
  { id: 1683, title: "Invalid Tweets", difficulty: "Easy", topic: "String",            url: "https://leetcode.com/problems/invalid-tweets/", done: false },
  { id: 1693, title: "Daily Leads and Partners", difficulty: "Easy", topic: "Aggregation", url: "https://leetcode.com/problems/daily-leads-and-partners/", done: false },
  { id: 1729, title: "Find Followers Count", difficulty: "Easy", topic: "Aggregation", url: "https://leetcode.com/problems/find-followers-count/", done: false },
  { id: 1731, title: "The Number of Employees Which Report to Each Employee", difficulty: "Easy", topic: "Joins", url: "https://leetcode.com/problems/the-number-of-employees-which-report-to-each-employee/", done: false },
  { id: 1741, title: "Find Total Time Spent by Each Employee", difficulty: "Easy", topic: "Aggregation", url: "https://leetcode.com/problems/find-total-time-spent-by-each-employee/", done: true },
  { id: 1757, title: "Recyclable and Low Fat Products", difficulty: "Easy", topic: "Basics", url: "https://leetcode.com/problems/recyclable-and-low-fat-products/", done: true },
  { id: 1789, title: "Primary Department for Each Employee", difficulty: "Easy", topic: "Window", url: "https://leetcode.com/problems/primary-department-for-each-employee/", done: false },
  { id: 1795, title: "Rearrange Products Table", difficulty: "Easy", topic: "Pivot",   url: "https://leetcode.com/problems/rearrange-products-table/", done: false },
  { id: 1873, title: "Calculate Special Bonus", difficulty: "Easy", topic: "String",   url: "https://leetcode.com/problems/calculate-special-bonus/", done: false },
  { id: 1890, title: "The Latest Login in 2020", difficulty: "Easy", topic: "Aggregation", url: "https://leetcode.com/problems/the-latest-login-in-2020/", done: false },
  { id: 1907, title: "Count Salary Categories", difficulty: "Medium", topic: "Aggregation", url: "https://leetcode.com/problems/count-salary-categories/", done: false },
  { id: 1934, title: "Confirmation Rate", difficulty: "Medium", topic: "Aggregation",  url: "https://leetcode.com/problems/confirmation-rate/", done: false },
  { id: 1965, title: "Employees With Missing Information", difficulty: "Easy", topic: "Joins", url: "https://leetcode.com/problems/employees-with-missing-information/", done: false },
  { id: 1978, title: "Employees Whose Manager Left the Company", difficulty: "Easy", topic: "Subqueries", url: "https://leetcode.com/problems/employees-whose-manager-left-the-company/", done: false },
  { id: 2356, title: "Number of Unique Subjects Taught by Each Teacher", difficulty: "Easy", topic: "Aggregation", url: "https://leetcode.com/problems/number-of-unique-subjects-taught-by-each-teacher/", done: true },
  { id: 3220, title: "Odd and Even Transactions", difficulty: "Medium", topic: "Aggregation", url: "https://leetcode.com/problems/odd-and-even-transactions/", done: false },
  { id: 3374, title: "First Letter Capitalization II", difficulty: "Hard", topic: "String", url: "https://leetcode.com/problems/first-letter-capitalization-ii/", done: false },
  { id: 3421, title: "Find Students Who Improved", difficulty: "Medium", topic: "Window", url: "https://leetcode.com/problems/find-students-who-improved/", done: false },
  { id: 3436, title: "Find Valid Emails", difficulty: "Easy", topic: "String",         url: "https://leetcode.com/problems/find-valid-emails/", done: false },
  { id: 3451, title: "Find Invalid IP Addresses", difficulty: "Hard", topic: "String", url: "https://leetcode.com/problems/find-invalid-ip-addresses/", done: false },
  { id: 3465, title: "Find Products with Valid Serial Numbers", difficulty: "Easy", topic: "String", url: "https://leetcode.com/problems/find-products-with-valid-serial-numbers/", done: false },
  { id: 3475, title: "DNA Pattern Recognition", difficulty: "Medium", topic: "String", url: "https://leetcode.com/problems/dna-pattern-recognition/", done: false },
  { id: 3482, title: "Analyze Organization Hierarchy", difficulty: "Hard", topic: "Window", url: "https://leetcode.com/problems/analyze-organization-hierarchy/", done: false },
  { id: 3497, title: "Analyze Subscription Conversion", difficulty: "Medium", topic: "Date", url: "https://leetcode.com/problems/analyze-subscription-conversion/", done: false },
  { id: 3521, title: "Find Product Recommendation Pairs", difficulty: "Medium", topic: "Joins", url: "https://leetcode.com/problems/find-product-recommendation-pairs/", done: false },
  { id: 3554, title: "Find Category Recommendation Pairs", difficulty: "Hard", topic: "Joins", url: "https://leetcode.com/problems/find-category-recommendation-pairs/", done: false },
  { id: 3564, title: "Seasonal Sales Analysis", difficulty: "Medium", topic: "Date",   url: "https://leetcode.com/problems/seasonal-sales-analysis/", done: false },
  { id: 3570, title: "Find Books with No Available Copies", difficulty: "Easy", topic: "Joins", url: "https://leetcode.com/problems/find-books-with-no-available-copies/", done: false },
  { id: 3580, title: "Find Consistently Improving Employees", difficulty: "Medium", topic: "Window", url: "https://leetcode.com/problems/find-consistently-improving-employees/", done: false },
  { id: 3586, title: "Find COVID Recovery Patients", difficulty: "Medium", topic: "Window", url: "https://leetcode.com/problems/find-covid-recovery-patients/", done: false },
  { id: 3601, title: "Find Drivers with Improved Fuel Efficiency", difficulty: "Medium", topic: "Window", url: "https://leetcode.com/problems/find-drivers-with-improved-fuel-efficiency/", done: false },
  { id: 3611, title: "Find Overbooked Employees", difficulty: "Medium", topic: "Aggregation", url: "https://leetcode.com/problems/find-overbooked-employees/", done: false },
  { id: 3617, title: "Find Students with Study Spiral Pattern", difficulty: "Hard", topic: "Window", url: "https://leetcode.com/problems/find-students-with-study-spiral-pattern/", done: false },
  { id: 3626, title: "Find Stores with Inventory Imbalance", difficulty: "Medium", topic: "Window", url: "https://leetcode.com/problems/find-stores-with-inventory-imbalance/", done: false },
  { id: 3642, title: "Find Books with Polarized Opinions", difficulty: "Medium", topic: "Aggregation", url: "https://leetcode.com/problems/find-books-with-polarized-opinions/", done: false },
  { id: 3657, title: "Find Loyal Customers", difficulty: "Medium", topic: "Aggregation", url: "https://leetcode.com/problems/find-loyal-customers/", done: false },
  { id: 3673, title: "Find Zombie Sessions", difficulty: "Hard", topic: "Window",      url: "https://leetcode.com/problems/find-zombie-sessions/", done: false },
  { id: 3705, title: "Find Golden Hour Customers", difficulty: "Medium", topic: "Date", url: "https://leetcode.com/problems/find-golden-hour-customers/", done: false },
  { id: 3716, title: "Find Churn Risk Customers", difficulty: "Medium", topic: "Window", url: "https://leetcode.com/problems/find-churn-risk-customers/", done: false },
  { id: 3764, title: "Most Common Course Pairs", difficulty: "Hard", topic: "Joins",   url: "https://leetcode.com/problems/most-common-course-pairs/", done: false },
  { id: 3793, title: "Find Users with High Token Usage", difficulty: "Easy", topic: "Aggregation", url: "https://leetcode.com/problems/find-users-with-high-token-usage/", done: false },
  { id: 3808, title: "Find Emotionally Consistent Users", difficulty: "Medium", topic: "Window", url: "https://leetcode.com/problems/find-emotionally-consistent-users/", done: false },
  { id: 3832, title: "Find Users with Persistent Behavior Patterns", difficulty: "Hard", topic: "Window", url: "https://leetcode.com/problems/find-users-with-persistent-behavior-patterns/", done: false },
];

// Real "date solved" values pulled from LeetCode submission history (YYYY-MM-DD), keyed by id.
// Used to seed `dateSolved` for already-solved problems so the timeline/heatmap/streak reflect
// actual practice days. Saved localStorage values always win over these, so editing in-app is safe.
// (#1757 isn't in the captured history, so it stays Solved without a date.)
const SOLVED_DATES = {
  175: "2026-06-21", 181: "2026-06-21", 182: "2026-06-21",
  176: "2026-06-22", 177: "2026-06-22", 183: "2026-06-22",
  197: "2026-06-23", 511: "2026-06-23", 577: "2026-06-23", 584: "2026-06-23", 595: "2026-06-23", 596: "2026-06-23",
  610: "2026-06-27",
  619: "2026-06-28",
  178: "2026-06-29", 180: "2026-06-29", 184: "2026-06-29", 185: "2026-06-29",
  196: "2026-06-30", 570: "2026-06-30",
  585: "2026-07-01", 586: "2026-07-01", 601: "2026-07-01", 602: "2026-07-01",
  607: "2026-07-01", 608: "2026-07-01", 620: "2026-07-01", 2356: "2026-07-01",
  1045: "2026-07-02", 1050: "2026-07-02", 1068: "2026-07-02", 1741: "2026-07-02",
};
